export const siteConfig = {
  brandName: "AlloStef",
  companyName: "AlloStef",
  legalEntityName: "StefPlomberie",
  legalForm: "micro-entreprise",
  siret: "909 840 795 00019",
  phoneDisplay: "06 15 26 78 47",
  phoneHref: "+33615267847",
  email: "allostef60@gmail.com",
  siteUrl: "https://allostef.fr",
  legalLastUpdated: "27 juillet 2026",
  privacyLastUpdated: "27 juillet 2026",
  serviceRadiusKm: 40,
  serviceCenterCommuneCode: "60395",
  serviceAreas: ["Oise", "Val-d’Oise"],
  services: [
    "Plomberie",
    "Chauffage",
    "Électricité",
    "Plâtrerie",
    "Carrelage",
    "Rénovation intérieure",
  ],
  navigation: [
    { label: "Services", href: "#services" },
    { label: "Zone d’intervention", href: "#zones" },
    { label: "Devis", href: "#devis" },
  ],
};
