export const siteConfig = {
  brandName: "AlloStef",
  companyName: "AlloStef",
  phoneDisplay: "06 12 34 56 78",
  phoneHref: "+33612345678",
  email: "contact@allostef.fr",
  siteUrl: "https://allostef.vercel.app",
  serviceRadiusKm: 40,
  serviceCenterCommuneCode: "60395",
  serviceAreas: ["Oise", "Val-d’Oise"],
  services: [
    "Plomberie",
    "Chauffage",
    "Électricité",
    "Plâtrerie",
    "Carrelage",
    "Rénovation intérieure",
  ],
  navigation: [
    { label: "Services", href: "#services" },
    { label: "Notre méthode", href: "#method" },
    { label: "Réalisations", href: "#realisations" },
    { label: "Zone d’intervention", href: "#zones" },
    { label: "Devis", href: "#devis" },
  ],
};
